
import math

# math.ceil(x) Arredonda para cima math.ceil(5.3) à 6

# math.copysign(x, y) Obtém um float com o valor absoluto de x, mas com o sinal de y

# math.copysign(-5.3, 1) à 5.3

# math.fabs(x) Valor absoluto de x math.fabs(-5.3) à 5.3

# math.floor(expr) Arredonda para baixo math.floor(5.3) à 5

# math.fmod(x, y) Resto da divisão de x por y (usar quando x ou y forem float, caso contrário usar %)

# math.fmod(5.4, 2) à 1.4

# math.trunc(x) Parte inteira de x math.trunc(5.6) à 5

# Constantes: 

# math.pi à 3.141592.

# math.e à 2.718281.

# math.exp(x) e**x math.exp(2) à 7.38905609893065

# math.log(x) Logaritmo natural de x (base e)

# math.log(2) à 0.6931471805599453

# math.log(x, y) Logaritmo de x na base y

# math.log(2, 10) à 0.30102999566398114

# math.pow(x, y) x**y math.pow(2, 3) à 8.0

# math.sqrt(x) Raiz quadrada de x math.sqrt(16) à 4.

# math.sin(x) Seno math.sin(0) à 0.0

# math.asin(x) Arco seno math.asin(1) à 1.5707963267948966

# math.cos(x) Cosseno math.cos(0) à 1.0

# math.acos(x) Arco cosseno math.acos(-1) à 3.141592653589793

# math.tan(x) Tangente math.tan(1) à 1.5574077246549023

# math.atan(x) Arco tangente math.atan(1) à 0.7853981633974483

# math.degrees(x) Converte radianos para graus math.degrees(math.pi) à 180.0

# math.radians(x) Converte graus para radianos math.radians(180) à 3.141592653589793

