
# Variável do lado esquerdo, valor ou expressão do lado direito
x = 0

print ( " x= " + x)

# Pode-se atribuir valor a várias varáveis ao mesmo tempo

x = y = z = 0 

# x, y e z terão valor 0

print ( " x= " + x)
print ( " y= " + x)

# Pode-se também atribuir valores diferentes para variáveis diferentes ao mesmo tempo

x, y = 1, 2 

# x terá o valor 1, e y terá o valor 2

print ( " x= " + x)
print ( " y= " + x)
